paths-ignore:
  # Block library contains example code with placeholder database URLs,
  # passwords, and tokens — none are real credentials
  - "blocks/library/**"

  # Verification/test projects contain example JWTs, keys, and high-entropy
  # test strings — all synthetic test data
  - "docs/book/verification/**"

  # Test files with intentional secret patterns for governance testing
  - "tests/governance/**"
  - "tests/governance_v3/**"

  # Security module contains test/example password hashing — not real secrets
  - "include/naab/secure_string.h"
