/*
 * Example: Agent Governance Middleware using NAAb C API
 *
 * Shows how to embed NAAb governance scanning as middleware in
 * an agent framework. Every code block generated by an LLM is
 * scanned before execution.
 *
 * Build:
 *   cc -I../../include/naab/public governance_middleware.c \
 *      -L../../build -lnaab-governance -o governance_middleware
 */

#include "naab_governance.h"
#include <stdio.h>
#include <stdlib.h>

int main(void) {
    printf("NAAb Governance Middleware Example\n");
    printf("Version: %s\n\n", naab_gov_version_string());

    /* 1. Create engine and load inline policy */
    naab_gov_engine_t eng = naab_gov_create();
    if (!eng) {
        fprintf(stderr, "Failed to create engine\n");
        return 1;
    }

    const char* policy =
        "{"
        "  \"version\": \"3.0\","
        "  \"mode\": \"enforce\","
        "  \"restrictions\": {"
        "    \"dangerous_calls\": { \"level\": \"hard\" },"
        "    \"code_injection\": { \"level\": \"hard\" }"
        "  },"
        "  \"code_quality\": {"
        "    \"no_secrets\": { \"level\": \"hard\" }"
        "  },"
        "  \"security\": { \"sandbox_level\": \"unrestricted\" }"
        "}";

    if (naab_gov_load_config_string(eng, policy) != NAAB_GOV_OK) {
        fprintf(stderr, "Config error: %s\n", naab_gov_last_error(eng));
        naab_gov_destroy(eng);
        return 1;
    }

    /* 2. Simulate scanning LLM-generated code blocks */
    const char* code_blocks[] = {
        "x = 42\nprint(f'Result: {x}')",           /* safe */
        "import os\nos.system('rm -rf /')",          /* dangerous */
        "api_key = 'AKIAIOSFODNN7EXAMPLE'",          /* secret leak */
    };
    const char* labels[] = {"safe math", "shell injection", "secret leak"};

    for (int i = 0; i < 3; i++) {
        printf("--- Scanning: %s ---\n", labels[i]);
        char* result = naab_gov_scan(eng, "python", code_blocks[i], "llm_output.py", 1);
        if (result) {
            printf("  Result: %.120s%s\n",
                   result, (strlen(result) > 120) ? "..." : "");
            printf("  Blocked: %s\n\n",
                   naab_gov_was_blocked(eng) ? "YES" : "no");
            naab_gov_free_string(result);
        }
        naab_gov_reset(eng);
    }

    naab_gov_destroy(eng);
    printf("Done.\n");
    return 0;
}
