#ifndef NAAB_CONFIG_H
#define NAAB_CONFIG_H

// Feature flags
#define NAAB_ENABLE_STRUCT_TYPES 1

// Version strings (temporary - should be generated by CMake)
#define NAAB_VERSION_STRING "0.2.0-dev"
#define NAAB_GIT_COMMIT_HASH "dev"
#define NAAB_GIT_HASH "dev"
#define NAAB_BUILD_TIMESTAMP "2026-01-07"
#define NAAB_API_VERSION "1.0"
#define NAAB_DATABASE_PATH "/data/data/com.termux/files/home/.naab/language/naab.db"

#endif // NAAB_CONFIG_H
