name: Bug Report
description: Report a bug in NAAb
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: NAAb code or steps that reproduce the issue.
      placeholder: |
        ```naab
        main {
          // your code here
        }
        ```
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened. Include error messages if applicable.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: NAAb Version
      description: Output of `naab-lang --version` or commit hash.
      placeholder: "v0.2.0"
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows (WSL)
        - Android (Termux)
        - Other
