name: Feature Request
description: Suggest a new feature for NAAb
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've considered.
  - type: textarea
    id: examples
    attributes:
      label: Code Examples
      description: Show how the feature would be used in NAAb code.
      placeholder: |
        ```naab
        main {
          // example usage
        }
        ```
