#!/usr/bin/env python3
"""Generate the nested-key schema the engine's config validator checks against.

WHY. validateSchema() only checked TOP-LEVEL govern.json keys, so a nested key
the loader never reads was accepted in silence. Measured across the 146 configs
in this repository: 330 such keys, including

  * agent_dispatch.hard_stop.max_calls       -- the loader reads max_calls_per_run,
                                                so the run has NO call budget
  * agents.<name>.timeout_seconds            -- agents read "timeout"
  * api.auth.keys[...]                       -- REST auth is api.keys; the whole
                                                endpoint stays unauthenticated
  * telemetry.forwarding.webhook_url         -- forwards nothing

Every one is a setting that looks configured and does nothing, and in each of the
cases above the silent default is the WEAKER one.

WHAT IS "KNOWN". Two sources, merged:
  1. every path loadFromJson() reads, from tools/template_coverage.py's walker
     (placeholder segments like <name> become the wildcard "*");
  2. keys govern-template.json documents, but ONLY at levels the loader itself
     reads named keys from. A template key the loader ignores is an INERT-key
     question (docs/findings/inert-config-keys.md), not a schema error, and the
     shipped template must load without warnings. Template keys under a value
     the loader reads whole (contract fixtures, example data) are not learned.

WHAT THE VALIDATOR DOES WITH IT (governance_checks.cpp, validateSchema):
  a key is reported only when its parent is a CLOSED level -- one where the
  loader reads named children. A level with no known children is an opaque value
  the loader reads whole, and is not descended into. Annotations (_*, rationale,
  *_rationale) are never reported.

The output is committed (src/runtime/governance_known_keys.inc) so the build
needs no Python. tests/governance_v4/test_nested_unknown_keys.sh regenerates it
and fails when it differs, so a loader change cannot leave the schema stale.

Run:  python3 tools/config_known_keys.py            (print to stdout)
      python3 tools/config_known_keys.py --write    (update the .inc)

Output is ASCII, written as bytes (see tools/screen_state_fields.py for why).
"""
import importlib.util
import json
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "src", "runtime", "governance_known_keys.inc")
TEMPLATE = os.path.join(REPO, "govern-template.json")
SEP = "\x1f"   # path separator: config keys may contain '.' or '/'


def load_extractor():
    spec = importlib.util.spec_from_file_location(
        "template_coverage", os.path.join(REPO, "tools", "template_coverage.py"))
    tc = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(tc)
    return tc


def build():
    tc = load_extractor()
    with open(tc.LOADER, "r", encoding="utf-8", errors="strict") as f:
        ex = tc.Extractor(f.read())
    ex.run()

    def norm(seg):
        return "*" if tc.is_placeholder(seg) else seg

    known = set()
    for p in ex.reads:
        q = tuple(norm(s) for s in p)
        for i in range(1, len(q) + 1):
            known.add(q[:i])
    if len(known) < 500:
        raise SystemExit("config_known_keys: only %d paths extracted -- the walk did "
                         "not run against the real loader" % len(known))

    loader_children = {}
    for k in known:
        loader_children.setdefault(k[:-1], set()).add(k[-1])

    def step(cands, seg):
        out = set()
        for c in cands:
            for s in (seg, "*"):
                if c + (s,) in known:
                    out.add(c + (s,))
        return out

    def closed(cands):
        return any(loader_children.get(c) for c in cands)

    def seed(v, cands):
        if isinstance(v, dict) and closed(cands):
            for k, x in v.items():
                if k.startswith("_"):
                    continue
                nc = step(cands, k)
                if not nc:
                    nc = {c + (k,) for c in cands}
                    known.update(nc)
                seed(x, nc)
        elif isinstance(v, list):
            nc = step(cands, "[]")
            for x in v:
                seed(x, nc)

    with open(TEMPLATE, "r", encoding="utf-8", errors="strict") as f:
        seed(json.load(f), {()})
    return sorted(SEP.join(k) for k in known)


def render(paths):
    lines = [
        "// GENERATED by tools/config_known_keys.py -- do not edit by hand.",
        "// Every nested govern.json path the engine reads, '*' = any key,",
        "// '[]' = array element, segments separated by \\x1f.",
        "// tests/governance_v4/test_nested_unknown_keys.sh fails when this is stale.",
    ]
    for p in paths:
        esc = p.replace("\\", "\\\\").replace('"', '\\"').replace(SEP, "\\x1f\"\"")
        lines.append('"%s",' % esc)
    return ("\n".join(lines) + "\n").encode("ascii")


def main(argv):
    data = render(build())
    if "--write" in argv:
        with open(OUT, "wb") as f:
            f.write(data)
        sys.stdout.buffer.write(b"wrote " + OUT.encode("ascii", "replace") + b"\n")
    else:
        sys.stdout.buffer.write(data)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
